language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

install:
   - composer install --no-dev

script: phpunit --configuration phpunit.xml

notifications:
  email:
    recipients:
      - sylvain@letsface.com
